# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "organic-growth"
client_id = "818249f8f4d6a7cbd647d1a04aa9e4e2"
application_url = "https://dreams-lynn-plaza-rare.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dreams-lynn-plaza-rare.trycloudflare.com/auth/callback",
  "https://dreams-lynn-plaza-rare.trycloudflare.com/auth/shopify/callback",
  "https://dreams-lynn-plaza-rare.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "farm-feedback.myshopify.com"
